services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: production
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
