name: eslinter check

on: [push, pull_request]

jobs:
  run_lint:
    permissions:
      contents: read
      packages: read
      pull-requests: read
      checks: write

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node Dependencies
        run: npm ci
        env:
          CI: TRUE
        working-directory: ./front

      - name: Check Code Linting
        run: npm run lint
        working-directory: ./front

      - name: Save Code Linting Report JSON
        run: npm run lint:report
        continue-on-error: true
        working-directory: ./front

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: "eslint_report.json"
